### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by alyhasansakr** [EdgeLab-FHDO/Latency-Measurement#2]
Develop the main architecture of the project including hardware and software.

**Comment by alyhasansakr** [comment]
![Latency_Measurement](https://user-images.githubusercontent.com/45193013/88819781-bcd19800-d1c0-11ea-97d5-54b00d85ac6d.png)

**Comment by alyhasansakr** [comment]
Our main target is to calculate how much time (E2EL) it takes from capturing an image to getting the actual output. Also to compare this time between running locally on user equipment (smartphone - Hololens) and remotely on an edge server.

**Comment by alyhasansakr** [comment]
Another proposal is from Willi, is to use a typical PC display (show a code on the screen) instead of a motor.
The problem is the display delay, normally this delay almost 50 ms, but the problem is that it is not predictable. A possible solution is to use a low latency display (gaming monitors) with high refresh rate (120 Hz). Then we compensate for the measured latency.

**Comment by alyhasansakr** [comment]
Instead of rotation motion, we may also have a linear motion.

**Comment by Satyam06** [comment]
![Capture](https://user-images.githubusercontent.com/14364179/89157435-261f2580-d58a-11ea-8517-7cd3631aa906.JPG)

**Comment by Satyam06** [comment]
This is another plausible setup, that can be used with a moving frame as discussed, for a calibrated time we can read the image and move forward to calculate the latency(E2EL).

**Comment by alyhasansakr** [comment]
How do we make the movement (motor, solenoid)? what kind of hardware do we use here?

**Comment by Satyam06** [comment]
For the movement, a motor for the reciprocating motion is required, if we go ahead with this plan. To measure the real time motion, we could use LVDTs.

Let me know what you think of the approach.

**Comment by alyhasansakr** [comment]
I think that is a good idea, so now we have two option:
1. Mechanical movement (linear or rotational).
1. Screen.
The first option is not currently possible because we can't go to the university, so I would say we go with the second option first. I will close this issue and write another issue for that.
